db.ventas.insert([
    {  
        "_id": 1, 
        "Artículo": "Nevera", 
        "Tipo" : "A",
        "Precio €": 505, 
        "Nº UD": 2, 
        "Fecha":new Date ("2020-08-23"), 
        "Cliente": "001", 
        "Fabricante": "Samnsung", 
        "Transporte": "SEUR", 
        "Premium": true
    },
    {"_id": 2, "Artículo": "Nevera" ,"Tipo" : "B", "Precio €" : 652, "Nº UD": 5, "Fecha": new Date ("2019-08-12"), "Cliente": "001", "Fabricante": "Zanussi", "Transporte": "NACEX","Premium": true},
    {"_id": 3, "Artículo": "Nevera" ,"Tipo" : "C", "Precio €" : 351, "Nº UD": 2, "Fecha": new Date ("2020-08-04"), "Cliente": "001", "Fabricante": "Samnsung", "Transporte": "SEUR", "Premium": true},
    {"_id": 4, "Artículo": "Nevera" ,"Tipo" : "D", "Precio €" : 547, "Nº UD": 7, "Fecha": new Date ("2019-05-21"), "Cliente": "002", "Fabricante": "Bosch", "Transporte": "NACEX", },
    {"_id": 5, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €" : 865, "Nº UD": 4, "Fecha": new Date ("2018-08-23"), "Cliente": "002", "Fabricante": "Samnsung", "Transporte": "SEUR",},
    {"_id": 6, "Artículo": "Nevera" ,"Tipo" : "B", "Precio €" : 966, "Nº UD": 2, "Fecha": new Date ("2019-01-25"), "Cliente": "002", "Fabricante": "Samnsung", "Transporte": "SEUR",},
    {"_id": 7, "Artículo": "Nevera" ,"Tipo" : "D", "Precio €" : 547, "Nº UD": 7, "Fecha": new Date ("2019-05-21"), "Cliente": "002", "Fabricante": "Bosch", "Transporte": "SEUR", },
    {"_id": 8, "Artículo": "Nevera" ,"Tipo" : "D", "Precio €" : 526, "Nº UD": 1, "Fecha": new Date ("2020-08-05"), "Cliente": "003", "Fabricante": "Samnsung", "Transporte": "SEUR", "Premium": true},
    {"_id": 9, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €" : 526, "Nº UD": 2, "Fecha": new Date ("2020-08-23"), "Cliente": "003", "Fabricante": "Zanussi", "Transporte": "MRW", },
    {"_id": 10, "Artículo": "Nevera" ,"Tipo" : "B", "Precio €": 789, "Nº UD": 4, "Fecha": new Date ("2019-08-23"), "Cliente": "004", "Fabricante": "Samnsung", "Transporte": "NACEX", "Premium": true},
    {"_id": 11, "Artículo": "Nevera" ,"Tipo" : "B", "Precio €": 268, "Nº UD": 2, "Fecha": new Date ("2020-04-14"), "Cliente": "004", "Fabricante": "Bosch", "Transporte": "SEUR", "Premium": true},
    {"_id": 12, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €": 664, "Nº UD": 2, "Fecha": new Date ("2020-08-23"), "Cliente": "004", "Fabricante": "Samnsung", "Transporte": "SEUR", "Premium": true},
    {"_id": 13, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €": 555, "Nº UD": 6, "Fecha": new Date ("2019-05-23"), "Cliente": "001", "Fabricante": "Zanussi", "Transporte": "SEUR", },
    {"_id": 14, "Artículo": "Nevera" ,"Tipo" : "C", "Precio €": 695, "Nº UD": 2, "Fecha": new Date ("2020-07-12"), "Cliente": "001", "Fabricante": "Bosch", "Transporte": "MRW", "Premium": true},
    {"_id": 15, "Artículo": "Nevera" ,"Tipo" : "D", "Precio €": 465, "Nº UD": 6, "Fecha": new Date ("2018-08-23"), "Cliente": "002", "Fabricante": "Zanussi", "Transporte": "SEUR", },
    {"_id": 16, "Artículo": "Nevera" ,"Tipo" : "D", "Precio €": 897, "Nº UD": 2, "Fecha": new Date ("2020-09-23"), "Cliente": "001", "Fabricante": "Samnsung", "Transporte": "NACEX", "Premium": true},
    {"_id": 17, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €": 663, "Nº UD": 3, "Fecha": new Date ("2019-08-08"), "Cliente": "003", "Fabricante": "Bosch", "Transporte": "SEUR", "Premium": true},
    {"_id": 18, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €": 298, "Nº UD": 9, "Fecha": new Date ("2020-11-23"), "Cliente": "001", "Fabricante": "Samnsung", "Transporte": "SEUR", "Premium": true},
    {"_id": 19, "Artículo": "Nevera" ,"Tipo" : "B", "Precio €": 775, "Nº UD": 2, "Fecha": new Date ("2019-08-19"), "Cliente": "004", "Fabricante": "Samnsung", "Transporte": "NACEX"},
    {"_id": 20, "Artículo": "Nevera" ,"Tipo" : "A", "Precio €": 912, "Nº UD": 5, "Fecha": new Date ("2018-12-23"), "Cliente": "001", "Fabricante": "Bosch", "Transporte": "MRW", },
    {"_id": 21, "Artículo": "Nevera" ,"Tipo" : "B", "Precio €": 885, "Nº UD": 4, "Fecha": new Date ("2018-08-29"), "Cliente": "003", "Fabricante": "Zanussi", "Transporte": "SEUR", "Premium": true},
]);